on:
  workflow_call: {}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Download Go packages
        shell: bash
        run: |
          go get ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: govulncheck
        shell: bash
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...

      - name: gosec # https://github.com/securego/gosec
        shell: bash
        run: |
          VERSION=$(curl -s https://api.github.com/repos/securego/gosec/releases/latest | jq -r ".tag_name" | cut -c2-)
          echo "Latest version is $VERSION"
          curl -O -L "https://github.com/securego/gosec/releases/download/v${VERSION}/gosec_${VERSION}_linux_amd64.tar.gz"
          tar -xvzf "gosec_${VERSION}_linux_amd64.tar.gz" -C "$(go env GOPATH)/bin" "gosec"
          chmod +x "$(go env GOPATH)/bin/gosec"
          gosec ./...
