name: ui-lint

on:
  workflow_call:
    inputs:
      working_dir:
        type: string
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ${{ inputs.working_dir }}/.nvmrc

      - name: Install dependencies
        working-directory: ${{ inputs.working_dir }}
        run: npm ci

      - name: Run Prettier
        working-directory: ${{ inputs.working_dir }}
        run: npx prettier --check .

      - name: Run knip
        working-directory: ${{ inputs.working_dir }}
        run: npx knip
